services:
  pg:
    image: postgres:16-alpine
    hostname: pg
    networks:
      - default
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: postgres
      POSTGRES_DB: dolphin
    volumes:
      - dolphin-pg-data:/var/lib/postgresql/data
  app:
    build: .
    hostname: dolphin-entrypoint
    networks:
      - default
      - dolphin
    environment:
      TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN}"
      ACCESS_TOKEN_SECRET: "${ACCESS_TOKEN_SECRET}"
      DB_HOST: pg
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: "${POSTGRES_PASSWORD}"
      DB_DATABASE: dolphin
    depends_on:
      - pg
volumes:
  dolphin-pg-data:
    external: true
networks:
  default:
  dolphin:
    external: true
