services:
  pg:
    image: postgres:16-alpine
    hostname: pg
    networks:
      - default
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: postgres
      POSTGRES_DB: dolphin
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - dolphin-pg-data:/var/lib/postgresql/data
  app:
    build: .
    hostname: dolphin-entrypoint
    networks:
      - default
      - dolphin
    environment:
      TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN}"
      TELEGRAM_MINI_APP_LINK: "${TELEGRAM_MINI_APP_LINK}"
      TELEGRAM_TEST_ENVIRONMENT: "${TELEGRAM_TEST_ENVIRONMENT}"
      ACCESS_TOKEN_SECRET: "${ACCESS_TOKEN_SECRET}"
      MINI_APP_URL: "${MINI_APP_URL}"
      DB_HOST: pg
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: "${POSTGRES_PASSWORD}"
      DB_DATABASE: dolphin
    depends_on:
      pg:
        condition: service_healthy
volumes:
  dolphin-pg-data:
    external: true
networks:
  default:
  dolphin:
    external: true
